// Generated by CoffeeScript 1.8.0
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use('/app/bower_components', function(req, res, next) {
    return res.redirect("/bower_components" + req.url);
  });

  app.use('/', express["static"]('../client'));

  app.listen(8100);

}).call(this);

//# sourceMappingURL=server.js.map
